### ISSUE TITLE
export .txt and import back function

### ISSUE THREAD

**Issue by BanhMi939** [MrEffectDev/XYZtext#1]
Could you make a function that can export the all of the text into 1 file .txt and then reimport it back to the files?

**Comment by MrEffectDev** [comment]
> Could you make a function that can export the all of the text into 1 file .txt and then reimport it back to the files?

Hello, I'll try to add this way

**Comment by BanhMi939** [comment]
> > Could you make a function that can export the all of the text into 1 file .txt and then reimport it back to the files?
> 
> Hello, I'll try to add this way

tysm brother.

**Comment by MrEffectDev** [comment]
> > > Could you make a function that can export the all of the text into 1 file .txt and then reimport it back to the files?
> > 
> > 
> > Hello, I'll try to add this way
> 
> tysm brother.

Hi again, I released a new version. To import back, you'll have to click File>Import from TXT. If you created a text file earlier, it won't work.

**Comment by MrEffectDev** [comment]
"Problem" was solved by adding a new function to the program

**Comment by BanhMi939** [comment]
So, now i can export all of the text to single txt file, translating it to my own language then reimport it back to working in game? Tysm for all of the work brother, this tool is so old, i was afraid no one will update it till i saw your fork.

**Comment by MrEffectDev** [comment]
> So, now i can export all of the text to single txt file, translating it to my own language then reimport it back to working in game? Tysm for all of the work brother, this tool is so old, i was afraid no one will update it till i saw your fork.

Can I have a star on my project, please? :)

**Comment by BanhMi939** [comment]
oh my bad, rated.

**Comment by MrEffectDev** [comment]
> oh my bad, rated.

Thank you

**Comment by BanhMi939** [comment]
btw, just one more question. Do you know why i get this error when trying to extract romfs from violet with trinity loader?
![image](https://github.com/MrEffectDev/XYZtext/assets/106416065/67b0ebdb-7ee7-4362-93dc-fa427dc1d26c)

**Comment by BanhMi939** [comment]
one more question, i've notice that my text dump do not included the text from DLC, it missing some file, found something called hashes_inside_fd.txt, do you know how to use this file in trinity loader to get the dlc text? Or could you sent me all of the text files included dlc from violet?

**Comment by MrEffectDev** [comment]
> one more question, i've notice that my text dump do not included the text from DLC, it missing some file, found something called hashes_inside_fd.txt, do you know how to use this file in trinity loader to get the dlc text? Or could you sent me all of the text files included dlc from violet?

Okay, how can I share it?

**Comment by BanhMi939** [comment]
> > one more question, i've notice that my text dump do not included the text from DLC, it missing some file, found something called hashes_inside_fd.txt, do you know how to use this file in trinity loader to get the dlc text? Or could you sent me all of the text files included dlc from violet?
> 
> Okay, how can I share it?
[GFPAKHashCache.zip](https://github.com/MrEffectDev/XYZtext/files/15396353/GFPAKHashCache.zip)

please make a zip of the file called "GFPAKHashCache.bin" from your trinityloader tool like this and paste it here.
![image](https://github.com/MrEffectDev/XYZtext/assets/106416065/ec1af3fc-9abe-45a0-b26e-c2f53088f824)

**Comment by BanhMi939** [comment]
btw, is this okay? when i'm trying to reimport the txt file?
![image](https://github.com/MrEffectDev/XYZtext/assets/106416065/b9ac639f-33db-4a84-988c-e3f0fb27bba6)

**Comment by BanhMi939** [comment]
okay, i ignored the Alert and then tested in the game, the game just crash.

**Comment by MrEffectDev** [comment]
> okay, i ignored the Alert and then tested in the game, the game just crash.

Write me in discord: mreffect_
